repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.7
    hooks:
      - id: uv-lock # Update the uv lockfile
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff # Run the linter.
        types_or: [ python, pyi ]
        args: [ --fix ]
        always_run: true
      - id: ruff-format # Run the formatter.
        types_or: [ python, pyi ]
        always_run: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'
    hooks:
      - id: mypy
        pass_filenames: false # no filenames will be passed to the hook.
        args: ['.']
        always_run: true
        verbose: true
  - repo: local
    hooks:
      - id: pytest
        name: unit-test
        entry: pytest test
        language: python
        pass_filenames: false # no filenames will be passed to the hook.
        always_run: true
        verbose: true
